# Test Runner Configuration
# Defines which test layers are enabled and their settings

test_layers:
  shell:
    enabled: true
    timeout: 300
    patterns:
      - "**/*.sh"
    description: "Shell script tests for existing functionality"
  
  unit:
    enabled: true
    description: "Layer 1: Unit tests for deterministic components"
    timeout: 300
    patterns:
      - "**/test_*.py"
      - "**/*_test.py"
  
  integration:
    enabled: true
    description: "Layer 2: Integration tests with MockClaudeProvider"
    timeout: 600
    patterns:
      - "**/test_*integration*.py"
    # Will test AI behavior with deterministic mocks
  
  contract:
    enabled: false
    description: "Layer 3: Contract-based AI validation"
    # Will validate AI outputs against YAML contracts
  
  chaos:
    enabled: false
    description: "Layer 4: Chaos and real AI tests"
    # Will test resilience and real AI behavior

# Global settings
timeout: 300  # Default timeout for all tests
results_dir: "test_results"